# Generated by Django 2.2.10 on 2020-10-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
