# Generated by Django 2.2.10 on 2020-10-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_publication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='upload',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
