# Generated by Django 2.2.10 on 2020-10-23 11:59

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20201022_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='upload',
            field=models.FileField(blank=True, max_length=255, upload_to=core.helpers.PathAndRename('cidb-qlassic/documents')),
        ),
    ]
