# Generated by Django 2.2.10 on 2020-10-27 08:44

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20201023_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_training', models.CharField(max_length=255, null=True)),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('publish', models.CharField(choices=[('publish', 'Publish'), ('do_not_publish', 'Do not publish')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='upload',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='publish',
            field=models.CharField(choices=[('publish', 'Publish'), ('do_not_publish', 'Do not publish')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('publications')),
        ),
        migrations.AddField(
            model_name='publication',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publish',
            field=models.CharField(choices=[('publish', 'Publish'), ('do_not_publish', 'Do not publish')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
