# Generated by Django 2.2.10 on 2020-11-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20201027_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='to_date',
        ),
    ]
