# Generated by Django 2.2.10 on 2020-11-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20201102_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
