# Generated by Django 2.2.10 on 2020-12-10 09:05

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20201210_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('template'))),
                ('template_type', models.CharField(choices=[('score_letter', 'Score letter'), ('qlassic_certificate', 'QLASSIC Certificate'), ('training_certificate', 'Training Certificate'), ('interview_letter', 'Interview Letter'), ('reject_letter', 'Reject Letter'), ('accreditation_letter', 'Accreditation Letter'), ('accreditation_certificate', 'Accreditation Certificate')], max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
