# Generated by Django 2.2.10 on 2020-12-10 09:05

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_lettertemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('templates')),
        ),
    ]
