# Generated by Django 2.2.10 on 2020-12-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20201210_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
