# Generated by Django 2.2.10 on 2020-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_lettertemplate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Use this template now?'),
        ),
    ]
