# Generated by Django 2.2.10 on 2020-12-16 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20201214_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='publish',
        ),
        migrations.AddField(
            model_name='training',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='available_seat',
            field=models.IntegerField(null=True, verbose_name='Available Seat'),
        ),
        migrations.AddField(
            model_name='training',
            name='ccd_point',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='CCD Point'),
        ),
        migrations.AddField(
            model_name='training',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Fees'),
        ),
        migrations.AddField(
            model_name='training',
            name='passing_mark',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Passing Mark'),
        ),
        migrations.AddField(
            model_name='training',
            name='postcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='training',
            name='state',
            field=models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='from_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='name_of_training',
            field=models.CharField(max_length=255, null=True, verbose_name='Training Name'),
        ),
        migrations.AlterField(
            model_name='training',
            name='to_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.CreateModel(
            name='TrainerTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('hp_no', models.CharField(max_length=15, null=True, verbose_name='Contact Number')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Training')),
            ],
        ),
    ]
