# Generated by Django 2.2.10 on 2020-12-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_training_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Published?'),
        ),
        migrations.DeleteModel(
            name='TrainerTraining',
        ),
    ]
