# Generated by Django 2.2.10 on 2020-12-22 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_auto_20201216_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplateConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('value', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
