# Generated by Django 2.2.10 on 2021-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_lettertemplateconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('score_letter', 'Score letter'), ('qlassic_certificate', 'QLASSIC Certificate'), ('training_certificate', 'Training Certificate'), ('interview_letter', 'Interview Letter'), ('reject_letter', 'Reject Letter'), ('attendance_sheet', 'Attendance Sheet'), ('accreditation_letter', 'Accreditation Letter'), ('accreditation_certificate', 'Accreditation Certificate')], max_length=20, null=True),
        ),
    ]
