# Generated by Django 2.2.10 on 2021-01-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20210120_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('score_letter', 'Score letter'), ('qlassic_certificate', 'QLASSIC Certificate'), ('training_certificate', 'Training Certificate'), ('trainer_interview_letter', 'Trainer Interview Letter'), ('qca_interview_letter', 'QCA Interview Letter'), ('trainer_reject_letter', 'Trainer Reject Letter'), ('qca_reject_letter', 'QCA Reject Letter'), ('attendance_sheet', 'Attendance Sheet'), ('accreditation_letter', 'Accreditation Letter'), ('accreditation_certificate', 'Accreditation Certificate')], max_length=20, null=True),
        ),
    ]
