# Generated by Django 2.2.10 on 2021-01-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20210121_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='publish',
            field=models.CharField(choices=[('publish', 'Publish'), ('do_not_publish', 'Do not publish')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('score_letter', 'Score letter'), ('qlassic_certificate', 'QLASSIC Certificate'), ('training_certificate', 'Training Certificate'), ('trainer_interview_letter', 'Trainer Interview Letter'), ('qca_interview_letter', 'QCA Interview Letter'), ('trainer_reject_letter', 'Trainer Reject Letter'), ('qca_reject_letter', 'QCA Reject Letter'), ('attendance_sheet', 'Attendance Sheet'), ('accreditation_letter', 'Accreditation Letter'), ('accreditation_certificate', 'Accreditation Certificate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publish',
            field=models.CharField(choices=[('publish', 'Publish'), ('do_not_publish', 'Do not publish')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='state',
            field=models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=50, null=True),
        ),
    ]
