# Generated by Django 2.2.10 on 2021-02-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20210121_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(choices=[('qlassic_score_letter', 'QLASSIC Score letter'), ('qlassic_certificate', 'QLASSIC Certificate'), ('qlassic_report', 'QLASSIC Report'), ('training_certificate', 'Training Certificate'), ('trainer_interview_letter', 'Trainer Interview Letter'), ('qca_interview_letter', 'QCA Interview Letter'), ('trainer_reject_letter', 'Trainer Reject Letter'), ('qca_reject_letter', 'QCA Reject Letter'), ('attendance_sheet', 'Attendance Sheet'), ('accreditation_letter', 'Accreditation Letter'), ('accreditation_certificate', 'Accreditation Certificate')], max_length=50, null=True),
        ),
    ]
