# Generated by Django 2.2.10 on 2020-10-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201020_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='greencard_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('0', 'Single'), ('1', 'Married'), ('2', 'Divorced'), ('3', 'Widowed'), ('NA', 'Not Available')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
