# Generated by Django 2.2.10 on 2020-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201021_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver'), ('contractor', 'Contractor'), ('trainer', 'Trainer'), ('trainee', 'Trainee'), ('applicant', 'Applicant'), ('assessor', 'Assessor'), ('NA', 'Not Available')], default='NA', max_length=20),
        ),
    ]
