# Generated by Django 2.2.10 on 2020-10-23 11:59

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201021_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('images')),
        ),
    ]
