# Generated by Django 2.2.10 on 2020-10-26 07:13

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201023_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fax_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='greencard_expiry_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='greencard_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='handphone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ic_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fax_no',
            field=models.CharField(max_length=12, null=True, verbose_name='Fax number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='greencard_exp_date',
            field=models.DateTimeField(null=True, verbose_name="Green card's expired date"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='greencard_no',
            field=models.CharField(max_length=16, null=True, verbose_name='Green card number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hp_no',
            field=models.CharField(max_length=12, null=True, verbose_name='Mobile number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='icno',
            field=models.CharField(max_length=12, null=True, verbose_name='Identity Card Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_no',
            field=models.CharField(max_length=12, null=True, verbose_name='Office phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('images'), verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postcode',
            field=models.IntegerField(null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('contractor', 'Contractor'), ('assessor', 'Assessor'), ('trainer', 'Trainer'), ('trainee', 'Trainee'), ('applicant', 'Applicant'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
