# Generated by Django 2.2.10 on 2020-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201026_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='year_from',
            field=models.IntegerField(null=True, verbose_name='Year start'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='year_to',
            field=models.IntegerField(null=True, verbose_name='Year end'),
        ),
    ]
