# Generated by Django 2.2.10 on 2020-10-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201026_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessor',
            name='assessor_number',
        ),
        migrations.AddField(
            model_name='assessor',
            name='assessor_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assessor number'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessor',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
