# Generated by Django 2.2.10 on 2020-10-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201026_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='assessor_no',
            field=models.CharField(max_length=6, null=True, verbose_name='Assessor number'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_no',
            field=models.CharField(max_length=6, null=True, verbose_name='Trainer number'),
        ),
    ]
