# Generated by Django 2.2.10 on 2020-11-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201028_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='greencard_exp_date',
        ),
    ]
