# Generated by Django 2.2.10 on 2020-11-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_customuser_greencard_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='greencard_exp_date',
            field=models.DateField(null=True, verbose_name="Green card's expired date"),
        ),
    ]
