# Generated by Django 2.2.10 on 2020-11-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201103_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
