# Generated by Django 2.2.10 on 2020-11-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201103_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='assessor_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Assessor number'),
        ),
    ]
