# Generated by Django 2.2.10 on 2020-12-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201111_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='transport_cc',
            field=models.FloatField(max_length=50, null=True, verbose_name='CC'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='transport_model',
            field=models.CharField(max_length=50, null=True, verbose_name='Transport Model'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='transport_registration_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Transport Registration Number'),
        ),
    ]
