# Generated by Django 2.2.10 on 2020-12-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201202_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='transport_cc',
            field=models.FloatField(null=True, verbose_name='CC'),
        ),
    ]
