# Generated by Django 2.2.10 on 2020-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20201202_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessor',
            name='transport_cc',
        ),
        migrations.RemoveField(
            model_name='assessor',
            name='transport_model',
        ),
        migrations.RemoveField(
            model_name='assessor',
            name='transport_registration_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='transport_cc',
            field=models.FloatField(null=True, verbose_name='CC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transport_model',
            field=models.CharField(max_length=50, null=True, verbose_name='Transport Model'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transport_registration_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Transport Registration Number'),
        ),
    ]
