# Generated by Django 2.2.10 on 2020-12-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201202_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='greencard_exp_date',
            field=models.DateField(blank=True, null=True, verbose_name="Green card's expired date"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='greencard_no',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Green card number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('contractor', 'Contractor'), ('assessor', 'Assessor'), ('trainer', 'Trainer'), ('trainee', 'Trainee'), ('applicant', 'Applicant'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver')], max_length=20, null=True),
        ),
    ]
