# Generated by Django 2.2.10 on 2020-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20201202_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fax_no',
            field=models.CharField(max_length=15, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hp_no',
            field=models.CharField(max_length=15, null=True, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='office_no',
            field=models.CharField(max_length=15, null=True, verbose_name='Office phone number'),
        ),
    ]
