# Generated by Django 2.2.10 on 2020-12-08 08:38

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20201208_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('images'), verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='transport_cc',
            field=models.FloatField(blank=True, null=True, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='transport_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transport Model'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='transport_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transport Registration Number'),
        ),
    ]
