# Generated by Django 2.2.10 on 2020-12-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20201208_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
