# Generated by Django 2.2.10 on 2020-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201208_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icno',
            field=models.CharField(max_length=20, null=True, verbose_name='Identity Card Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal code'),
        ),
    ]
