# Generated by Django 2.2.10 on 2020-12-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20201214_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icno',
            field=models.CharField(max_length=14, null=True, verbose_name='Identity Card Number'),
        ),
    ]
