# Generated by Django 2.2.10 on 2020-12-23 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0017_auto_20201216_1501'),
        ('users', '0034_auto_20201216_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='assessor_type',
            field=models.CharField(choices=[('QIA', 'QLASSIC Industry Assessor'), ('QCA', 'QLASSIC CIDB Assessor')], default='QIA', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationAssessor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='', max_length=255, null=True)),
                ('reviewed_by', models.CharField(max_length=255, null=True)),
                ('approved_by', models.CharField(max_length=255, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.Payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
