# Generated by Django 2.2.10 on 2020-12-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201223_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationAssessor',
        ),
    ]
