# Generated by Django 2.2.10 on 2021-01-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_delete_applicationassessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicqualification',
            name='qualification',
            field=models.CharField(choices=[('spm', 'SPM'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('master', 'Master'), ('phd', 'PHD')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assessor',
            name='assessor_type',
            field=models.CharField(choices=[('QIA', 'QLASSIC Industry Assessor'), ('QCA', 'QLASSIC CIDB Assessor')], default='QIA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff'), ('contractor', 'Contractor'), ('assessor', 'Assessor'), ('trainer', 'Trainer'), ('trainee', 'Trainee'), ('applicant', 'Applicant'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=50, null=True),
        ),
    ]
