# Generated by Django 2.2.10 on 2020-10-20 06:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('building_category', models.CharField(blank=True, max_length=255)),
                ('construction_method', models.CharField(blank=True, max_length=255)),
                ('levy_number', models.CharField(blank=True, max_length=255)),
                ('project_value', models.FloatField(null=True)),
                ('status_levy_payment', models.CharField(blank=True, max_length=255)),
                ('architect_firm', models.CharField(blank=True, max_length=255)),
                ('structural_civil_firm', models.CharField(blank=True, max_length=255)),
                ('mechanical_electrical_firm', models.CharField(blank=True, max_length=255)),
                ('gfa', models.FloatField(null=True)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('iso_9001', models.CharField(blank=True, max_length=255)),
                ('shassiq', models.CharField(blank=True, max_length=255)),
                ('bim', models.CharField(blank=True, max_length=255)),
                ('gbi', models.CharField(blank=True, max_length=255)),
                ('mycrest', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('qaa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('postcode', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('company_registration_number', models.CharField(blank=True, max_length=255)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('representative_email', models.CharField(blank=True, max_length=255)),
                ('representative_hp_number', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project_info', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('postcode', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('cidb_registration_number', models.CharField(blank=True, max_length=255)),
                ('cidb_registration_grade', models.CharField(blank=True, max_length=255)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('representative_email', models.CharField(blank=True, max_length=255)),
                ('representative_hp_number', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('project_info', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectInfo')),
            ],
        ),
    ]
