# Generated by Django 2.2.10 on 2020-10-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='city',
            new_name='city1',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='address1',
            new_name='correspondence_address1',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='address2',
            new_name='correspondence_address2',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='postcode',
            new_name='postcode1',
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='state',
            new_name='state1',
        ),
        migrations.AddField(
            model_name='contractor',
            name='city2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contractor',
            name='postcode2',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='registered_address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contractor',
            name='registered_address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contractor',
            name='state2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
