# Generated by Django 2.2.10 on 2020-10-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201022_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='building_category',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='iso_9001',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_value',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='status_levy_payment',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='structural_civil_firm',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='title',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='contract_value',
            field=models.CharField(max_length=5, null=True, verbose_name='Contract value (including GST)'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='contractor_cidb_registration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='contractor_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='contractor_registration_grade',
            field=models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('g4', 'G4'), ('g5', 'G5'), ('g6', 'G6'), ('g7', 'G7')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='developer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='developer_ssm_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='hp_no',
            field=models.CharField(max_length=12, null=True, verbose_name='Contact number'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='iso9001',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='phase',
            field=models.CharField(max_length=10, null=True, verbose_name='Project phase'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_manager',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='rating_type',
            field=models.CharField(choices=[('qlassic', 'QLASSIC'), ('mock_up', 'Mock up')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='site_representative',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='structural_civil_engineer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='architect_firm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='bim',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have BIM'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='construction_method',
            field=models.CharField(choices=[('ibs', 'IBS'), ('conventional', 'Conventional'), ('design_and_build', 'Design & Build'), ('pfi', 'PFI')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='gbi',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have GBI'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='gfa',
            field=models.FloatField(null=True, verbose_name='Gross Floor Area (meter square)'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='levy_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='mechanical_electrical_firm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='mycrest',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have MyCREST'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='qaa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='shassiq',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have SHASSIQ'),
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
