# Generated by Django 2.2.10 on 2020-10-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201027_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='cidb_registration_grade',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='cidb_registration_number',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='city1',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='city2',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='correspondence_address1',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='correspondence_address2',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='postcode1',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='postcode2',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='project_info',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='registered_address1',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='registered_address2',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='representative_email',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='representative_hp_number',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='representative_name',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='state1',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='state2',
        ),
        migrations.AddField(
            model_name='contractor',
            name='client_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_registration_grade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_registration_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='correspondence_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='dateline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='letter_of_award_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='name_of_contractor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='project_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='project_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='registered_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government')], max_length=10, null=True, verbose_name='Project type @ Sector'),
        ),
    ]
