# Generated by Django 2.2.10 on 2020-11-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201027_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='dateline',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='letter_of_award_date',
        ),
        migrations.RemoveField(
            model_name='contractor',
            name='start_date',
        ),
    ]
