# Generated by Django 2.2.10 on 2020-11-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20201102_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='dateline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='letter_of_award_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
