# Generated by Django 2.2.10 on 2020-11-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20201102_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='contract_type',
            field=models.CharField(choices=[('lump_sum', 'Lump Sum'), ('provisional_quantity', 'Provisional Quantity'), ('lum_sump_and_quantity', 'Lump Sum and Quantity')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contract_value',
            field=models.CharField(max_length=5, null=True, verbose_name='Contract value (including GST)'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='levy_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='project_type',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government')], max_length=10, null=True, verbose_name='Project type @ Sector'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='ssm_number',
            field=models.CharField(max_length=10, null=True, verbose_name='SSM number'),
        ),
    ]
