# Generated by Django 2.2.10 on 2020-11-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201103_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contract_value',
            field=models.CharField(max_length=10, null=True, verbose_name='Contract value (including GST)'),
        ),
    ]
