# Generated by Django 2.2.10 on 2020-11-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201103_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='building_type',
            field=models.CharField(choices=[('a', 'A - Landed Housing'), ('b', 'B - Stratified Housing'), ('c', 'C - Public/ Commercial/ Industrial Building (Without centralized cooling system)'), ('d', 'D - Public/ Commercial/ Industrial Building (With centralized cooling system)')], max_length=20, null=True),
        ),
    ]
