# Generated by Django 2.2.10 on 2020-11-03 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_contractor_building_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='building_type',
        ),
    ]
