# Generated by Django 2.2.10 on 2020-11-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_contractor_building_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='shassiq',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='shassic',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have SHASSIQ?'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='bim',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have BIM?'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='gbi',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have GBI?'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='iso9001',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have ISO 9001?'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='mycrest',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have MyCREST?'),
        ),
    ]
