# Generated by Django 2.2.10 on 2020-11-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20201103_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='structural_civil_engineer',
            new_name='structural_civil_engineer_firm',
        ),
    ]
