# Generated by Django 2.2.10 on 2020-11-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20201103_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='qaa_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Qlassic Assessment Application number'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='mechanical_electrical_firm',
            field=models.CharField(max_length=255, null=True, verbose_name='M&E Engineer Firm'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='structural_civil_engineer_firm',
            field=models.CharField(max_length=255, null=True, verbose_name='Structural & Civil Engineer Firm'),
        ),
    ]
