# Generated by Django 2.2.10 on 2020-11-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20201103_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='project_location',
            field=models.CharField(choices=[('ME', 'Melaka'), ('JH', 'Johor'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('TE', 'Terengganu'), ('KN', 'Kelantan'), ('PK', 'Perak'), ('PL', 'Perlis'), ('KH', 'Kedah'), ('SL', 'Selangor'), ('KL', 'Kuala Lumpur'), ('SA', 'Sabah'), ('SW', 'Sarawak'), ('PG', 'Pulau Pinang')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='project_type',
            field=models.CharField(choices=[('P', 'Private'), ('G', 'Government')], max_length=10, null=True, verbose_name='Project type @ Sector'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_type',
            field=models.CharField(choices=[('P', 'Private'), ('G', 'Government')], max_length=10, null=True, verbose_name='Project type @ Sector'),
        ),
    ]
