# Generated by Django 2.2.10 on 2020-11-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20201103_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contract_value',
            field=models.CharField(max_length=10, null=True, verbose_name='Contract value (RM including GST)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='qaa_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Qlassic Assessment Application number'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='contract_value',
            field=models.CharField(max_length=5, null=True, verbose_name='Contract value (RM including GST)'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_location',
            field=models.CharField(choices=[('ME', 'Melaka'), ('JH', 'Johor'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('TE', 'Terengganu'), ('KN', 'Kelantan'), ('PK', 'Perak'), ('PL', 'Perlis'), ('KH', 'Kedah'), ('SL', 'Selangor'), ('KL', 'Kuala Lumpur'), ('SA', 'Sabah'), ('SW', 'Sarawak'), ('PG', 'Pulau Pinang')], max_length=255, null=True),
        ),
    ]
