# Generated by Django 2.2.10 on 2020-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20201111_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contractor_registration_grade',
            field=models.CharField(choices=[('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('g4', 'G4'), ('g5', 'G5'), ('g6', 'G6'), ('g7', 'G7')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='shassic',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True, verbose_name='Does the project have SHASSIC?'),
        ),
    ]
