# Generated by Django 2.2.10 on 2020-12-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20201117_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='contractor_cidb_registration',
            new_name='contractor_cidb_registration_no',
        ),
    ]
