# Generated by Django 2.2.10 on 2020-12-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20201201_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='project_reference_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_reference_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
