# Generated by Django 2.2.10 on 2020-12-08 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_verifiedcontractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='contract_value',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='contract_value',
        ),
    ]
