# Generated by Django 2.2.10 on 2020-12-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20201208_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Contract value (RM including GST)'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Contract value (RM including GST)'),
        ),
    ]
