# Generated by Django 2.2.10 on 2020-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20201208_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contractor_registration_grade',
            field=models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('G7', 'G7')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='levy_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='qaa_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qlassic Assessment Application number'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='ssm_number',
            field=models.CharField(max_length=50, null=True, verbose_name='SSM number'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='contractor_registration_grade',
            field=models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('G7', 'G7')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='developer_ssm_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='hp_no',
            field=models.CharField(max_length=15, null=True, verbose_name='Contact number'),
        ),
    ]
