# Generated by Django 2.2.10 on 2020-12-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20201208_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='correspondence_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='correspondence_postcode',
            field=models.IntegerField(null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='correspondence_state',
            field=models.CharField(choices=[('ME', 'Melaka'), ('JH', 'Johor'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('TE', 'Terengganu'), ('KN', 'Kelantan'), ('PK', 'Perak'), ('PL', 'Perlis'), ('KH', 'Kedah'), ('SL', 'Selangor'), ('KL', 'Kuala Lumpur'), ('SA', 'Sabah'), ('SW', 'Sarawak'), ('PG', 'Pulau Pinang')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='registered_city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='registered_postcode',
            field=models.IntegerField(null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='registered_state',
            field=models.CharField(choices=[('ME', 'Melaka'), ('JH', 'Johor'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('TE', 'Terengganu'), ('KN', 'Kelantan'), ('PK', 'Perak'), ('PL', 'Perlis'), ('KH', 'Kedah'), ('SL', 'Selangor'), ('KL', 'Kuala Lumpur'), ('SA', 'Sabah'), ('SW', 'Sarawak'), ('PG', 'Pulau Pinang')], max_length=20, null=True),
        ),
    ]
