# Generated by Django 2.2.10 on 2020-12-08 18:15

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20201208_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='levy_receipt',
            field=models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('documents')),
        ),
    ]
