# Generated by Django 2.2.10 on 2020-12-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_projectinfo_levy_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='correspondence_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='correspondence_state',
            field=models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='registered_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='registered_state',
            field=models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True),
        ),
    ]
