# Generated by Django 2.2.10 on 2020-12-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20201209_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='project_title',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_title',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
