# Generated by Django 2.2.10 on 2020-12-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20201210_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='correspondence_postcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='registered_postcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal code'),
        ),
    ]
