# Generated by Django 2.2.10 on 2020-12-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20201214_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='ibs_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='IBS percentage (%)'),
        ),
    ]
