# Generated by Django 2.2.10 on 2020-12-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_projectinfo_ibs_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='ibs_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IBS percentage (%)'),
        ),
    ]
