# Generated by Django 2.2.10 on 2020-12-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20201215_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
