# Generated by Django 2.2.10 on 2020-12-15 09:40

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_contractor_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='levy_receipt',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.helpers.PathAndRename('documents')),
        ),
    ]
