# Generated by Django 2.2.10 on 2020-12-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20201216_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('lump_sum', 'Lump Sum'), ('provisional_quantity', 'Provisional Quantity'), ('lum_sump_and_quantity', 'Lump Sum and Quantity')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Contract value (RM including GST)'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_registration_grade',
            field=models.CharField(blank=True, choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('G6', 'G6'), ('G7', 'G7')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='correspondence_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='correspondence_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='correspondence_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='correspondence_state',
            field=models.CharField(blank=True, choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='dateline',
            field=models.DateField(blank=True, null=True, verbose_name='Dateline'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='letter_of_award_date',
            field=models.DateField(blank=True, null=True, verbose_name='Letter of Award Date'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='levy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name_of_contractor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='project_location',
            field=models.CharField(blank=True, choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='project_reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='project_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='project_type',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'PRIVATE'), ('GOVERNMENT', 'GOVERNMENT')], max_length=10, null=True, verbose_name='Project type @ Sector'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='registered_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='registered_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='registered_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='registered_state',
            field=models.CharField(blank=True, choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='ssm_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SSM number'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
