# Generated by Django 2.2.10 on 2021-01-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20201217_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='qaa',
        ),
    ]
