# Generated by Django 2.2.10 on 2021-01-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_remove_projectinfo_qaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('lump_sum', 'Lump Sum'), ('provisional_quantity', 'Provisional Quantity'), ('lum_sump_and_quantity', 'Lump Sum and Quantity')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='construction_method',
            field=models.CharField(choices=[('ibs', 'IBS'), ('conventional', 'Conventional'), ('design_and_build', 'Design & Build'), ('pfi', 'PFI')], max_length=50, null=True),
        ),
    ]
