# Generated by Django 2.2.10 on 2020-10-20 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billings', '0001_initial'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='assessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='payment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billings.Payment'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='element',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defectgroup',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentdata',
            name='assessor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor'),
        ),
        migrations.AddField(
            model_name='assessmentdata',
            name='defect_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.DefectGroup'),
        ),
        migrations.AddField(
            model_name='assessmentdata',
            name='element',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Element'),
        ),
        migrations.AddField(
            model_name='assessmentdata',
            name='qaa',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication'),
        ),
    ]
