# Generated by Django 2.2.10 on 2020-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20201020_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectgroup',
            name='defect_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_name',
            field=models.CharField(max_length=255),
        ),
    ]
