# Generated by Django 2.2.10 on 2020-10-23 11:59

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20201022_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdata',
            name='picture',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('cidb-qlassic/images')),
        ),
    ]
