# Generated by Django 2.2.10 on 2020-10-26 07:13

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20201023_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdata',
            name='picture',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('images')),
        ),
    ]
