# Generated by Django 2.2.10 on 2020-10-27 02:03

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
        ('trainings', '0007_auto_20201026_0904'),
        ('assessments', '0005_auto_20201026_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('documents'))),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('application_date', models.DateTimeField()),
                ('proposed_date', models.DateTimeField()),
                ('assessment_start_date', models.DateTimeField()),
                ('assessment_end_date', models.DateTimeField()),
                ('number_of_days', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('at', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.ApplicationTrainer')),
                ('jt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.JoinedTraining')),
                ('payment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='billings.Payment')),
                ('qaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
        ),
    ]
