# Generated by Django 2.2.10 on 2020-10-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_supportingdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='assessment_end_date',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='assessment_start_date',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='assessor',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='supportingdocuments',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='supportingdocuments',
            name='assessment_end_date',
        ),
        migrations.RemoveField(
            model_name='supportingdocuments',
            name='assessment_start_date',
        ),
        migrations.RemoveField(
            model_name='supportingdocuments',
            name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='supportingdocuments',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='supportingdocuments',
            name='proposed_date',
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='address1',
            field=models.CharField(max_length=255, null=True, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='address2',
            field=models.CharField(max_length=255, null=True, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='applicant_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('Approved', 'Approved')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='approved_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='assessment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='building_type',
            field=models.CharField(choices=[('a', 'A - Landed Housing'), ('b', 'B - Stratified Housing'), ('c', 'C - Public/ Commercial/ Industrial Building (Without centralized cooling system)'), ('d', 'D - Public/ Commercial/ Industrial Building (With centralized cooling system)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='contract_type',
            field=models.CharField(choices=[('lump_sum', 'Lump Sum'), ('provisional_quantity', 'Provisional Quantity'), ('lum_sump_and_quantity', 'Lump Sum and Quantity')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='fax_no',
            field=models.CharField(max_length=12, null=True, verbose_name='Fax number'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='hp_no',
            field=models.CharField(max_length=12, null=True, verbose_name='Contact number'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='no_of_assessor',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8'), (10, '10')], null=True, verbose_name='Number of assessor'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='no_of_blocks',
            field=models.IntegerField(null=True, verbose_name='Number of block'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='organization',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='payment_mode',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='postcode',
            field=models.IntegerField(null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='project_declaration_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='qaa_number',
            field=models.CharField(max_length=7, null=True, verbose_name='QLASSIC Assessment Application Number'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='remarks1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='remarks2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='remarks3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='reviewed_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='reviewed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('contractor', 'Contractor'), ('assessor', 'Assessor'), ('trainer', 'Trainer'), ('trainee', 'Trainee'), ('applicant', 'Applicant'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='verified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='verified_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='proposed_date',
            field=models.DateTimeField(null=True, verbose_name='Proposed date for assessment'),
        ),
    ]
