# Generated by Django 2.2.10 on 2020-10-27 06:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201026_0813'),
        ('assessments', '0007_auto_20201027_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocuments',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportingdocuments',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='SuggestedAssessor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_location', models.CharField(max_length=255, null=True)),
                ('assessor_no', models.CharField(max_length=255, null=True, verbose_name='Assessor number')),
                ('role_in_project', models.CharField(max_length=255, null=True)),
                ('acception', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor')),
                ('qaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
        ),
    ]
