# Generated by Django 2.2.10 on 2020-10-27 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201026_0813'),
        ('assessments', '0008_auto_20201027_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedAssessor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessor_number', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('role_in_assessment', models.CharField(choices=[('lead_assessor', 'Lead Assessor'), ('assessor', 'Assessor')], max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor')),
            ],
        ),
    ]
