# Generated by Django 2.2.10 on 2020-10-27 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201026_0813'),
        ('assessments', '0009_assignedassessor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCompletionForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessor_number', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('icno', models.CharField(max_length=255, null=True, verbose_name='IC number')),
                ('company', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('hp_no', models.CharField(max_length=255, null=True, verbose_name='Contact number')),
                ('email', models.CharField(max_length=255, null=True)),
                ('qaa_number', models.CharField(max_length=255, null=True, verbose_name='QLASSIC Assessment Application number')),
                ('project_location', models.CharField(max_length=255, null=True)),
                ('assessment_start_date', models.DateTimeField(null=True)),
                ('assessment_end_date', models.DateTimeField(null=True)),
                ('number_of_sample', models.IntegerField(null=True)),
                ('number_of_form_used', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentData')),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor')),
                ('qaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
        ),
    ]
