# Generated by Django 2.2.10 on 2020-10-27 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_workcompletionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectgroup',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Element'),
        ),
        migrations.AddField(
            model_name='defectgroup',
            name='element_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defectgroup',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defectgroup',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='defectgroup',
            name='defect_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defectgroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='element',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
