# Generated by Django 2.2.10 on 2020-10-27 07:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_auto_20201027_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='QlassicReporting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qaa_number', models.CharField(max_length=255, null=True)),
                ('report_number', models.CharField(max_length=255, null=True)),
                ('type_of_report', models.CharField(choices=[('qlassic_score_letter', 'QLASSIC Score Letter'), ('qlassic_certificate', 'QLASSIC Certificate'), ('qlassic_report', 'QLASSIC Report')], max_length=30, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentData')),
                ('qaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
        ),
    ]
