# Generated by Django 2.2.10 on 2020-10-27 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_qlassicreporting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qaa_no', models.CharField(max_length=255, null=True, verbose_name='QLASSIC Assessment Application number')),
                ('name', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('hp_no', models.CharField(max_length=255, null=True, verbose_name='Contact number')),
                ('company', models.CharField(max_length=255, null=True)),
                ('signature', models.CharField(max_length=255, null=True)),
                ('assessment_date', models.DateTimeField(null=True)),
                ('report_number', models.CharField(max_length=255, null=True)),
                ('type_of_report', models.CharField(choices=[('qlassic_score_letter', 'QLASSIC Score Letter'), ('qlassic_certificate', 'QLASSIC Certificate'), ('qlassic_report', 'QLASSIC Report')], max_length=30, null=True)),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentData')),
                ('qaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication')),
            ],
        ),
    ]
