# Generated by Django 2.2.10 on 2020-11-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_auto_20201027_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='approved_date',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='assessment_date',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='proposed_date',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='reviewed_date',
        ),
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='verified_date',
        ),
        migrations.RemoveField(
            model_name='siteattendance',
            name='assessment_date',
        ),
        migrations.RemoveField(
            model_name='workcompletionform',
            name='assessment_end_date',
        ),
        migrations.RemoveField(
            model_name='workcompletionform',
            name='assessment_start_date',
        ),
    ]
