# Generated by Django 2.2.10 on 2020-11-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_auto_20201102_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='approved_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='assessment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='proposed_date',
            field=models.DateField(null=True, verbose_name='Proposed date for assessment'),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='reviewed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='verified_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='siteattendance',
            name='assessment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workcompletionform',
            name='assessment_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workcompletionform',
            name='assessment_start_date',
            field=models.DateField(null=True),
        ),
    ]
