# Generated by Django 2.2.10 on 2020-11-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20201103_0632'),
        ('assessments', '0019_auto_20201103_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Contractor'),
        ),
    ]
