# Generated by Django 2.2.10 on 2020-11-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_qlassicassessmentapplication_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='no_of_blocks',
            field=models.IntegerField(null=True, verbose_name='Number of block/zone/assessment'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='qaa_number',
            field=models.CharField(max_length=50, null=True, verbose_name='QLASSIC Assessment Application Number'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='remarks1',
            field=models.CharField(max_length=255, null=True, verbose_name='Remarks 1 - by CASC Reviewer'),
        ),
    ]
