# Generated by Django 2.2.10 on 2020-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_auto_20201104_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='reviewed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='verified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
