# Generated by Django 2.2.10 on 2020-11-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_auto_20201104_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='remarks1',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Remarks 1 - by CASC Reviewer'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='remarks2',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='remarks3',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
