# Generated by Django 2.2.10 on 2020-11-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_auto_20201106_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('need_payment', 'Need Payment'), ('paid', 'Paid'), ('assessor_assign', 'Assessor Assign'), ('confirm', 'Confirm'), ('in_progress', 'In-Progress'), ('completed', 'Completed'), ('approved', 'Approved')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='remarks2',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Remarks 2 - by CASC Verifier'),
        ),
    ]
