# Generated by Django 2.2.10 on 2020-11-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_auto_20201116_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedassessor',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentData'),
        ),
    ]
