# Generated by Django 2.2.10 on 2020-12-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_assignedassessor_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='qlassic_score',
            field=models.FloatField(blank=True, null=True, verbose_name='QLASSIC Score'),
        ),
    ]
