# Generated by Django 2.2.10 on 2020-12-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_qlassicassessmentapplication_qlassic_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='fax_no',
            field=models.CharField(max_length=15, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='hp_no',
            field=models.CharField(max_length=15, null=True, verbose_name='Contact number'),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='icno',
            field=models.CharField(max_length=12, null=True, verbose_name='IC number'),
        ),
    ]
