# Generated by Django 2.2.10 on 2020-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_auto_20201208_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='organization',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
