# Generated by Django 2.2.10 on 2020-12-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0033_auto_20201208_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qlassicassessmentapplication',
            name='contractor',
        ),
    ]
