# Generated by Django 2.2.10 on 2020-12-10 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_auto_20201209_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectgroup',
            name='element',
        ),
        migrations.RemoveField(
            model_name='defectgroup',
            name='element_name',
        ),
        migrations.RemoveField(
            model_name='defectgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='element',
            name='user',
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='assessment_date',
            field=models.DateField(null=True, verbose_name='Assessment date'),
        ),
        migrations.AlterField(
            model_name='siteattendance',
            name='assessment_date',
            field=models.DateField(null=True, verbose_name='Assessment date'),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='assessment_end_date',
            field=models.DateField(null=True, verbose_name='Assessment end date'),
        ),
        migrations.AlterField(
            model_name='workcompletionform',
            name='assessment_start_date',
            field=models.DateField(null=True, verbose_name='Assessment start date'),
        ),
        migrations.CreateModel(
            name='SubElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_element_name', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Element')),
            ],
        ),
        migrations.AddField(
            model_name='defectgroup',
            name='sub_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SubElement'),
        ),
    ]
