# Generated by Django 2.2.10 on 2020-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0036_auto_20201210_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcompletionform',
            name='icno',
            field=models.CharField(max_length=20, null=True, verbose_name='IC number'),
        ),
    ]
