# Generated by Django 2.2.10 on 2020-12-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_auto_20201221_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectgroupresult',
            name='checked',
        ),
        migrations.AddField(
            model_name='defectgroupresult',
            name='acception',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='defectgroupresult',
            name='applicable',
            field=models.BooleanField(default=True),
        ),
    ]
