# Generated by Django 2.2.10 on 2020-12-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0043_auto_20201222_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentdata',
            name='dg',
        ),
        migrations.RemoveField(
            model_name='assessmentdata',
            name='element',
        ),
    ]
