# Generated by Django 2.2.10 on 2020-12-22 04:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_auto_20201222_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='defectgroupresult',
            name='acception',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_type',
        ),
        migrations.AddField(
            model_name='defectgroupresult',
            name='score',
            field=models.IntegerField(choices=[(0, 'Fail'), (1, 'Pass')], default=0, null=True),
        ),
    ]
