# Generated by Django 2.2.10 on 2020-12-22 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0045_auto_20201222_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='element_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.ElementType'),
        ),
    ]
