# Generated by Django 2.2.10 on 2021-01-02 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0047_auto_20201222_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportingdocuments',
            name='at',
        ),
    ]
