# Generated by Django 2.2.10 on 2021-01-02 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0048_remove_supportingdocuments_at'),
        ('trainings', '0041_auto_20210102_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocuments',
            name='ra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.RoleApplication'),
        ),
    ]
