# Generated by Django 2.2.10 on 2021-01-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0049_supportingdocuments_ra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirement',
            new_name='Component',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='requirement',
            new_name='component',
        ),
    ]
