# Generated by Django 2.2.10 on 2021-01-04 04:18

import core.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0050_auto_20210104_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Component')),
            ],
        ),
        migrations.CreateModel(
            name='SubComponentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('assessment_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentData')),
                ('sub_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SubComponent')),
            ],
        ),
        migrations.CreateModel(
            name='SubComponentResultDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('results'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('sub_component_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SubComponentResult')),
            ],
        ),
        migrations.RemoveField(
            model_name='elementresultdocument',
            name='element_result',
        ),
        migrations.RemoveField(
            model_name='subelement',
            name='element',
        ),
        migrations.RenameField(
            model_name='defectgroup',
            old_name='defect_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='element',
            old_name='element_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='defectgroup',
            name='sub_element',
        ),
        migrations.RemoveField(
            model_name='element',
            name='component',
        ),
        migrations.AddField(
            model_name='defectgroup',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.Element'),
        ),
        migrations.DeleteModel(
            name='ElementResult',
        ),
        migrations.DeleteModel(
            name='ElementResultDocument',
        ),
        migrations.DeleteModel(
            name='SubElement',
        ),
        migrations.AddField(
            model_name='element',
            name='sub_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.SubComponent'),
        ),
    ]
