# Generated by Django 2.2.10 on 2021-01-18 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_remove_projectinfo_qaa'),
        ('assessments', '0051_auto_20210104_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='qlassicassessmentapplication',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectInfo'),
        ),
    ]
