# Generated by Django 2.2.10 on 2021-01-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0052_qlassicassessmentapplication_pi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='building_type',
            field=models.CharField(choices=[('A', 'A - Landed Housing'), ('B', 'B - Stratified Housing'), ('C', 'C - Public/ Commercial/ Industrial Building (Without centralized cooling system)'), ('D', 'D - Public/ Commercial/ Industrial Building (With centralized cooling system)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='contract_type',
            field=models.CharField(choices=[('lump_sum', 'Lump Sum'), ('provisional_quantity', 'Provisional Quantity'), ('lum_sump_and_quantity', 'Lump Sum and Quantity')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='project_declaration_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('contractor', 'Contractor'), ('assessor', 'Assessor'), ('trainer', 'Trainer'), ('trainee', 'Trainee'), ('applicant', 'Applicant'), ('casc_reviewer', 'CASC Reviewer'), ('casc_verifier', 'CASC Verifier'), ('casc_approver', 'CASC Approver'), ('cidb_reviewer', 'CIDB Reviewer'), ('cidb_verifier', 'CIDB Verifier'), ('cidb_approver', 'CIDB Approver')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlassicassessmentapplication',
            name='state',
            field=models.CharField(choices=[('MELAKA', 'MELAKA'), ('JOHOR', 'JOHOR'), ('NEGERI SEMBILAN', 'NEGERI SEMBILAN'), ('PAHANG', 'PAHANG'), ('TERENGGANU', 'TERENGGANU'), ('KELANTAN', 'KELANTAN'), ('PERAK', 'PERAK'), ('PERLIS', 'PERLIS'), ('KEDAH', 'KEDAH'), ('SELANGOR', 'SELANGOR'), ('WILAYAH PERSEKUTUAN KUALA LUMPUR', 'KUALA LUMPUR'), ('SABAH', 'SABAH'), ('SARAWAK', 'SARAWAK'), ('PULAU PINANG', 'PULAU PINANG')], max_length=50, null=True),
        ),
    ]
