# Generated by Django 2.2 on 2021-08-02 03:31

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0053_auto_20210507_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlassicreporting',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('assessment/report/', 'a'), verbose_name='Report File'),
        ),
    ]
