# Generated by Django 2.2.10 on 2020-10-20 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_name', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('card_number', models.IntegerField(null=True)),
                ('card_expired_date', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=255)),
                ('payment_type', models.CharField(blank=True, max_length=255)),
                ('receipt_id', models.UUIDField(default=uuid.uuid4)),
                ('invoice_id', models.UUIDField(default=uuid.uuid4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
