# Generated by Django 2.2.10 on 2020-10-27 07:52

import core.helpers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_category', models.CharField(choices=[('mileage', 'Mileage')], max_length=10, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('mileage', models.FloatField(null=True)),
                ('total_receipt_amount', models.FloatField(null=True)),
                ('date_of_transaction', models.DateTimeField(null=True)),
                ('attachments', models.FileField(max_length=255, null=True, upload_to=core.helpers.PathAndRename('billings'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
