# Generated by Django 2.2.10 on 2020-10-27 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_qlassicreporting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billings', '0002_claimapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_expired_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qaa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('online_banking', 'Online Banking'), ('credit_debit_card', 'Credit/ Debit card')], max_length=20, null=True),
        ),
    ]
