# Generated by Django 2.2.10 on 2020-10-27 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billings', '0003_auto_20201027_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_description', models.CharField(max_length=255, null=True)),
                ('account_type', models.CharField(choices=[('saving_account', 'Saving Account')], max_length=20, null=True)),
                ('account_bank', models.CharField(choices=[('cimbclicks', 'CIMB Clicks'), ('maybank2u', 'Maybank2u'), ('affinbank', 'Affin Bank'), ('bsn', 'Bank Simpanan Nasional')], max_length=20, null=True)),
                ('account_number', models.CharField(max_length=15, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
