# Generated by Django 2.2.10 on 2020-10-27 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_onlinebanking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDebitCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_no', models.CharField(max_length=20, null=True, verbose_name='Credit/ Debit card number')),
                ('name_on_card', models.CharField(max_length=255, null=True)),
                ('expired_date', models.DateTimeField(null=True, verbose_name='Expired date (month/year)')),
                ('cvc', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='onlinebanking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='onlinebanking',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='onlinebanking',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='onlinebanking',
            name='modified_date',
        ),
    ]
