# Generated by Django 2.2.10 on 2020-10-27 10:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_auto_20201027_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_description', models.CharField(max_length=255, null=True)),
                ('receipt_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice')], max_length=20, null=True)),
                ('receipt_description', models.CharField(max_length=255, null=True)),
                ('cdc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.CreditDebitCard')),
                ('ob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.OnlineBanking')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.Payment')),
            ],
        ),
    ]
