# Generated by Django 2.2.10 on 2020-10-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_remove_registrationtraining_payment'),
        ('billings', '0006_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.RegistrationTraining'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingCertificate'),
        ),
    ]
