# Generated by Django 2.2.10 on 2020-11-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_auto_20201028_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditdebitcard',
            name='expired_date',
        ),
    ]
