# Generated by Django 2.2.10 on 2020-11-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_remove_creditdebitcard_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdebitcard',
            name='expired_date',
            field=models.DateField(null=True, verbose_name='Expired date (month/year)'),
        ),
    ]
