# Generated by Django 2.2.10 on 2020-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0009_creditdebitcard_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='location_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='location_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='other_type',
            field=models.CharField(choices=[('mileage', 'Mileage'), ('fi', 'FI'), ('public_transport', 'Public Transport'), ('accommodation', 'Accommodation'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='receipt_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='state_from',
            field=models.CharField(choices=[('ME', 'Melaka'), ('JH', 'Johor'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('TE', 'Terengganu'), ('KN', 'Kelantan'), ('PK', 'Perak'), ('PL', 'Perlis'), ('KH', 'Kedah'), ('SL', 'Selangor'), ('KL', 'Kuala Lumpur'), ('SA', 'Sabah'), ('SW', 'Sarawak'), ('PG', 'Pulau Pinang')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='state_to',
            field=models.CharField(choices=[('ME', 'Melaka'), ('JH', 'Johor'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('TE', 'Terengganu'), ('KN', 'Kelantan'), ('PK', 'Perak'), ('PL', 'Perlis'), ('KH', 'Kedah'), ('SL', 'Selangor'), ('KL', 'Kuala Lumpur'), ('SA', 'Sabah'), ('SW', 'Sarawak'), ('PG', 'Pulau Pinang')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='claimapplication',
            name='claim_category',
            field=models.CharField(choices=[('mileage', 'Mileage'), ('fi', 'FI'), ('public_transport', 'Public Transport'), ('accommodation', 'Accommodation'), ('others', 'Others')], max_length=20, null=True),
        ),
    ]
