# Generated by Django 2.2.10 on 2020-11-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_auto_20201117_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
    ]
