# Generated by Django 2.2.10 on 2020-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0011_auto_20201118_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimapplication',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='claimapplication',
            name='date_to',
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='time_to',
            field=models.TimeField(null=True),
        ),
    ]
