# Generated by Django 2.2.10 on 2020-11-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0012_auto_20201118_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimapplication',
            name='date_of_transaction',
            field=models.DateField(null=True),
        ),
    ]
