# Generated by Django 2.2.10 on 2020-12-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0013_auto_20201118_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='transport_cc',
            field=models.FloatField(null=True, verbose_name='CC'),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='transport_model',
            field=models.CharField(max_length=50, null=True, verbose_name='Transport Model'),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='transport_registration_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Transport Registration Number'),
        ),
    ]
