# Generated by Django 2.2.10 on 2021-01-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0018_claimapplication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimapplication',
            name='total_receipt_amount',
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='accommodation_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('lojing', 'Lojing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='transport_type',
            field=models.CharField(choices=[('airplane', 'Airplane'), ('train', 'Train'), ('car', 'Car'), ('bus', 'Bus')], max_length=20, null=True),
        ),
    ]
