# Generated by Django 2.2.10 on 2021-01-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0053_auto_20210121_1655'),
        ('trainings', '0048_auto_20210122_1742'),
        ('billings', '0021_auto_20210121_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='qaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.QlassicAssessmentApplication'),
        ),
        migrations.AddField(
            model_name='claimapplication',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training'),
        ),
    ]
