# Generated by Django 2.2.10 on 2021-01-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0022_auto_20210126_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='claim_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('verified', 'Verified'), ('approved', 'Approved')], default='pending', max_length=50, null=True),
        ),
    ]
