# Generated by Django 2.2.10 on 2021-01-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0023_claimapplication_claim_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='code_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
