# Generated by Django 2.2.10 on 2021-01-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0024_claimapplication_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimapplication',
            name='zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
