# Generated by Django 2.2.10 on 2020-10-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20201020_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedtraining',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='joinedtraining',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joinedtraining',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joinedtraining',
            name='place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='joinedtraining',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Year join the training'),
        ),
    ]
