# Generated by Django 2.2.10 on 2020-10-26 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20201026_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Marks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=255, null=True, verbose_name="Participant's name")),
                ('attendance_full', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('marks', models.FloatField(null=True)),
                ('rt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.RegistrationTraining')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training')),
            ],
        ),
    ]
