# Generated by Django 2.2.10 on 2020-10-26 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_attendance_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance_Marks',
            new_name='AttendanceMarks',
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='amount',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_email',
            field=models.CharField(max_length=20, null=True, verbose_name="Participant's email"),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_hpno',
            field=models.CharField(max_length=12, null=True, verbose_name="Participant's phone number"),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_icno',
            field=models.CharField(max_length=12, null=True, verbose_name="Participant's IC number"),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_name',
            field=models.CharField(max_length=50, null=True, verbose_name="Participant's name"),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='reviewed_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_type', models.CharField(choices=[('module1', 'Module 1'), ('module2', 'Module 2'), ('exam_practical_test', 'Exam Practical Test')], max_length=255, null=True)),
                ('participant_name', models.CharField(max_length=255, null=True, verbose_name="Participant's name")),
                ('attendance_full', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True)),
                ('marks', models.FloatField(null=True)),
                ('certificate_description', models.CharField(choices=[('attendance', 'Attendance'), ('marks', 'Marks')], max_length=10, null=True)),
                ('fees', models.CharField(max_length=4, null=True)),
                ('reviewed_by', models.CharField(max_length=4, null=True)),
                ('reviewed_date', models.DateTimeField(null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=10, null=True)),
                ('rt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.RegistrationTraining')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training')),
            ],
        ),
    ]
