# Generated by Django 2.2.10 on 2020-10-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20201026_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtrainer',
            name='status',
        ),
        migrations.AddField(
            model_name='applicationtrainer',
            name='application_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('reject', 'Reject'), ('pending', 'Pending')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationtrainer',
            name='approved_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationtrainer',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicationtrainer',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicationtrainer',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationtrainer',
            name='reviewed_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingcertificate',
            name='reviewed_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
