# Generated by Django 2.2.10 on 2020-10-28 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20201026_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtraining',
            name='payment',
        ),
    ]
