# Generated by Django 2.2.10 on 2020-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20201102_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='from_date',
            field=models.DateField(null=True, verbose_name='Date start'),
        ),
        migrations.AddField(
            model_name='training',
            name='to_date',
            field=models.DateField(null=True, verbose_name='Date end'),
        ),
    ]
