# Generated by Django 2.2.10 on 2020-11-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_auto_20201102_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcertificate',
            name='reviewed_date',
        ),
    ]
