# Generated by Django 2.2.10 on 2020-11-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0011_remove_trainingcertificate_reviewed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcertificate',
            name='reviewed_date',
            field=models.DateField(null=True),
        ),
    ]
