# Generated by Django 2.2.10 on 2020-11-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0012_trainingcertificate_reviewed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='state',
            field=models.CharField(choices=[('Melaka', 'Melaka'), ('Johor', 'Johor'), ('Negeri Sembilan', 'Negeri Sembilan'), ('Pahang', 'Pahang'), ('Terengganu', 'Terengganu'), ('Kelantan', 'Kelantan'), ('Perak', 'Perak'), ('Perlis', 'Perlis'), ('Kedah', 'Kedah'), ('Selangor', 'Selangor'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak'), ('Pulau Pinang', 'Pulau Pinang')], max_length=255, null=True),
        ),
    ]
