# Generated by Django 2.2.10 on 2020-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0016_auto_20201208_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_icno',
            field=models.CharField(max_length=20, null=True, verbose_name="Participant's IC number"),
        ),
    ]
