# Generated by Django 2.2.10 on 2020-12-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0017_auto_20201214_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='postcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal code'),
        ),
    ]
