# Generated by Django 2.2.10 on 2020-12-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0020_auto_20201216_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='coach',
        ),
        migrations.AddField(
            model_name='training',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Fees'),
        ),
        migrations.AlterField(
            model_name='training',
            name='ccd_point',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='CCD Point'),
        ),
        migrations.AlterField(
            model_name='training',
            name='cert_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('pass', 'Pass')], max_length=30, null=True, verbose_name='Certificate Type'),
        ),
        migrations.AlterField(
            model_name='training',
            name='from_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='passing_mark',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Passing Mark'),
        ),
        migrations.AlterField(
            model_name='training',
            name='postcode',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='training',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Available Seat'),
        ),
        migrations.AlterField(
            model_name='training',
            name='to_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('hp_no', models.CharField(max_length=15, null=True, verbose_name='Contact Number')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.Training')),
            ],
        ),
    ]
