# Generated by Django 2.2.10 on 2020-12-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0021_auto_20201216_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='publish',
        ),
    ]
