# Generated by Django 2.2.10 on 2020-12-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0023_training_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Training Name'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
