# Generated by Django 2.2.10 on 2020-12-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0025_auto_20201217_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='training',
            name='reviewed_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='reviewed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Fees (RM)'),
        ),
    ]
