# Generated by Django 2.2.10 on 2020-12-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0026_auto_20201218_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
