# Generated by Django 2.2.10 on 2020-12-23 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0027_auto_20201223_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationtraining',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='registrationtraining',
            name='training_type',
        ),
        migrations.AddField(
            model_name='registrationtraining',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationtraining',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
