# Generated by Django 2.2.10 on 2020-12-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0028_auto_20201223_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtraining',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('need_payment', 'Need Payment')], default='pending', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
