# Generated by Django 2.2.10 on 2020-12-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0029_registrationtraining_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtraining',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Remarks'),
        ),
    ]
