# Generated by Django 2.2.10 on 2020-12-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0030_registrationtraining_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtraining',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Amount (RM)'),
        ),
    ]
