# Generated by Django 2.2.10 on 2020-12-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0031_auto_20201223_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtrainer',
            name='application_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('reject', 'Reject'), ('pending', 'Pending')], default='', max_length=255, null=True),
        ),
    ]
