# Generated by Django 2.2.10 on 2020-12-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0032_auto_20201223_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtrainer',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='', max_length=255, null=True),
        ),
    ]
