# Generated by Django 2.2.10 on 2020-12-29 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0034_auto_20201223_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtraining',
            name='attendance_full',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='registrationtraining',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='created_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='AttendanceMarks',
        ),
    ]
