# Generated by Django 2.2.10 on 2020-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0035_auto_20201229_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attendance_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('need_approval', 'Submit For Approval'), ('approved', 'Approved')], default='pending', max_length=20, null=True, verbose_name='Attendance Review Status'),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='attendance_full',
            field=models.BooleanField(blank=True, choices=[(True, 'FULL'), (False, 'NOT FULL')], null=True),
        ),
    ]
