# Generated by Django 2.2.10 on 2020-12-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0037_auto_20201230_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainings.TrainingType'),
        ),
    ]
