# Generated by Django 2.2.10 on 2020-12-31 02:28

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0038_training_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtraining',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('certificates'), verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='required_for_assessor',
            field=models.BooleanField(default=False, null=True, verbose_name='Required For Becoming Assessor?'),
        ),
    ]
