# Generated by Django 2.2.10 on 2021-01-02 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_delete_applicationassessor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billings', '0017_auto_20201216_1501'),
        ('assessments', '0048_remove_supportingdocuments_at'),
        ('trainings', '0040_auto_20201231_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='', max_length=255, null=True)),
                ('application_type', models.CharField(choices=[('qca', 'QLASSIC CIDB Assessor'), ('trainer', 'Trainer')], default='', max_length=255, null=True)),
                ('reviewed_by', models.CharField(max_length=255, null=True)),
                ('approved_by', models.CharField(max_length=255, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Assessor')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billings.Payment')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Trainer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationtrainer',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='applicationtrainer',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='applicationtrainer',
            name='user',
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount (RM)'),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_email',
            field=models.CharField(max_length=100, null=True, verbose_name="Participant's email"),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_name',
            field=models.CharField(max_length=200, null=True, verbose_name="Participant's name"),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('need_payment', 'Need Payment')], default='pending', max_length=40, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='training',
            name='attendance_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('need_approval', 'Submit For Approval'), ('approved', 'Approved')], default='pending', max_length=40, null=True, verbose_name='Attendance Review Status'),
        ),
        migrations.AlterField(
            model_name='training',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=40, null=True, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='ApplicationAssessor',
        ),
        migrations.DeleteModel(
            name='ApplicationTrainer',
        ),
    ]
