# Generated by Django 2.2.10 on 2021-01-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0041_auto_20210102_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Rejected')], default='', max_length=255, null=True),
        ),
    ]
