# Generated by Django 2.2.10 on 2021-01-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0042_auto_20210104_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
