# Generated by Django 2.2.10 on 2021-01-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0043_roleapplication_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='interview_location',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='interview_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
