# Generated by Django 2.2.10 on 2021-01-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0044_auto_20210107_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtraining',
            name='participant_designation',
            field=models.CharField(max_length=200, null=True, verbose_name="Participant's name"),
        ),
        migrations.AddField(
            model_name='registrationtraining',
            name='participant_organization',
            field=models.CharField(max_length=200, null=True, verbose_name="Participant's name"),
        ),
        migrations.AddField(
            model_name='registrationtraining',
            name='participant_organization_type',
            field=models.CharField(choices=[('contractor', 'Contractor'), ('developer', 'Developer'), ('consultant', 'Consultant'), ('individual ', 'Individual')], default=True, max_length=5, null=True),
        ),
    ]
