# Generated by Django 2.2.10 on 2021-01-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0045_auto_20210120_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='from_time',
            field=models.TimeField(null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='training',
            name='to_time',
            field=models.TimeField(null=True, verbose_name='End Time'),
        ),
    ]
