# Generated by Django 2.2.10 on 2021-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0046_auto_20210121_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleapplication',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='roleapplication',
            name='interview_time',
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_organization_type',
            field=models.CharField(choices=[('Contractor', 'Contractor'), ('Developer', 'Developer'), ('Consultant', 'Consultant'), ('Individual ', 'Individual')], default=True, max_length=50, null=True),
        ),
    ]
