# Generated by Django 2.2.10 on 2021-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0047_auto_20210122_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='interview_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='interview_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roleapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interview_invitation', 'Interview Invitation'), ('approved', 'Approved'), ('reject', 'Rejected')], default='', max_length=255, null=True),
        ),
    ]
