# Generated by Django 2.2.10 on 2021-01-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0049_auto_20210129_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_designation',
            field=models.CharField(max_length=200, null=True, verbose_name="Participant's designation"),
        ),
        migrations.AlterField(
            model_name='registrationtraining',
            name='participant_organization',
            field=models.CharField(max_length=200, null=True, verbose_name="Participant's organization"),
        ),
    ]
