# Generated by Django 2.2.10 on 2021-01-29 03:05

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0050_auto_20210129_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attendance_sheet_file',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('attendance_sheet'), verbose_name='Attendance Sheet'),
        ),
    ]
