# Generated by Django 2.2.10 on 2021-02-01 06:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0051_training_attendance_sheet_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_id', models.CharField(max_length=50, null=True)),
                ('description_1', models.TextField(blank=True, max_length=3000, null=True)),
                ('description_2', models.TextField(blank=True, max_length=3000, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
