# Generated by Django 2.2.10 on 2021-02-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0054_auto_20210201_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='warning',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='warning_delivered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
