# Generated by Django 2.2.10 on 2021-02-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0055_auto_20210202_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='delivered_date',
            new_name='warning_delivered_date',
        ),
    ]
