# Generated by Django 2.2.10 on 2020-10-26 07:13

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(null=True, upload_to=core.helpers.PathAndRename('documents')),
        ),
    ]
