# Generated by Django 2.2.10 on 2020-10-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201026_0713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
